# this is a flow to test deploy to S3

name: Deploy to S3

on:
  push:
    branches: 
      - main

jobs:
  deploy-S3:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SOURCE_DIR: ./assets/icon.png
    steps: 
      - name: S3 Deploy
        uses: Reggionick/s3-deploy@v3.1.1
        with:
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: us-west-1

