# this is a flow to test deploy to S3

name: Deploy to S3

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  deploy-S3:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: S3 Deploy
        uses: Reggionick/s3-deploy@v3.1.1
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}/build
          bucket-region: us-west-1
          private: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

